### ISSUE TITLE
How do you set gcp_credentials?

### ISSUE THREAD

**Issue by kaihendry** [google-github-actions/deploy-cloud-functions#18]
### Question

Say I download the service account details JSON, how do I use it to set gcp_credentials?

```
[
  "auth_provider_x509_cert_url",
  "auth_uri",
  "client_email",
  "client_id",
  "client_x509_cert_url",
  "private_key",
  "private_key_id",
  "project_id",
  "token_uri",
  "type"
]
```

**Comment by highway7** [comment]
@kaihendry On your Github repo page, following [Repo] -> Settings -> Secrets -> New Repo Secret, and add the JSON Key details in the Value box.

**Comment by bharathkkb** [comment]
Hi @kaihendry 
@highway7 has outlined the steps to add the secret. Once that is done, you can reference it as shown [here](https://github.com/google-github-actions/deploy-cloud-functions#usage). Docs here: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

Feel free to reopen if needed.

**Comment by kaihendry** [comment]
Ok, thanks. I guess my confusion is that I didn't expect to copy an entire JSON object as the secret. I was expecting a short one line string / password
