### ISSUE TITLE
Support for vpc_connector_egress_settings

### ISSUE THREAD

**Issue by ajazfarhad** [google-github-actions/deploy-cloud-functions#197]
### Question
i'm getting following warning on adding `vpc_connector_egress_settings` flag in my action file

`Warning: Unexpected input(s) 'vpc_connector_egress_settings', valid inputs are ['credentials', 'name', 'description', 'project_id', 'region', 'source_dir', 'env_vars', 'env_vars_file', 'labels', 'entry_point', 'runtime', 'memory_mb', 'vpc_connector', 'service_account_email', 'timeout', 'max_instances', 'event_trigger_type', 'event_trigger_resource', 'event_trigger_service']`

I just wanted to confirm if this option is still supported.

**Comment by sethvargo** [comment]
`vpc_connector_egress_settings` is supported and was added in https://github.com/google-github-actions/deploy-cloud-functions/commit/d5dec313cb9c6f9c5464bf45570c9fe674152357. Please make sure you're using the latest version of the action.
