### ISSUE TITLE
Build overrides for displaying a Version indicator

### ISSUE THREAD

**Issue by kaihendry** [google-github-actions/deploy-cloud-functions#23]
### TL;DR

I need to know what version of the function is running for  `--runtime go113`

I need to be able to do something like:

    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags -X main.Version=$(git describe --always) -o server *.go

**Comment by bharathkkb** [comment]
Hi @kaihendry 
Could you elaborate on the request a bit more. Did you mean you would like an output with what is the current deployed version after the deployment is complete?

**Comment by sethvargo** [comment]
Closing due to lack of response.
