### ISSUE TITLE
Service Account mix-up in docs?

### ISSUE THREAD

**Issue by uschtwill** [google-github-actions/deploy-cloud-functions#25]
### Question
Is it possible, that the documentation/README is incorrect in specifying that the created service account should be added as a member to the "**Compute Engine** default service account"? And that instead it should be added as a member to the "**App Engine** default service Account"? At least that's how it works for me, and that's also the guidance I am getting from the job logs:

```Error: Missing necessary permission iam.serviceAccounts.actAs for $MEMBER on the service account PROJECT_ID@appspot.gserviceaccount.com.```

In my project `PROJECT_ID@appspot.gserviceaccount.com` is the **App engine** default service account, whereas the **Compute engine** one is called `PROJECT_NUMBER-compute@developer.gserviceaccount.com`.

...raising this as a question, as it seems so obvious that I am suspecting I am doing something wrong.

**Comment by bharathkkb** [comment]
@uschtwill Thanks for the report, looks like this is a mix-up. Cloud Functions does default to `PROJECT_ID@appspot.gserviceaccount.com` and deploying SA needs actAs on this SA.

**Comment by sethvargo** [comment]
The README is up to date now!
