### ISSUE TITLE
Please add support for security-level flag

### ISSUE THREAD

**Issue by songololo** [google-github-actions/deploy-cloud-functions#261]
### TL;DR

Please add support for the GCP cloud functions deploy `--security-level` parameter.

### Detailed design

```markdown
Per the docs:
https://cloud.google.com/sdk/gcloud/reference/functions/deploy

--security-level=SECURITY_LEVEL; default="secure-always"
Security level controls whether a function's URL supports HTTPS only or both HTTP and HTTPS. By default, secure-always will be used, meaning only HTTPS is supported. SECURITY_LEVEL must be one of: secure-always, secure-optional.
```

### Additional information

This would be convenient for deploying `HTTPS` functions. Currently, it is necessary to manually edit the function from the console after deploy to enable `HTTPS` only.

**Comment by ma185360** [comment]
@songololo  Hi Team, Any update this one. This is very basic and important feature.
