### ISSUE TITLE
Add env_vars_file option

### ISSUE THREAD

**Issue by ryan-blunden** [google-github-actions/deploy-cloud-functions#32]
### TL;DR

It does not seem possible to generate environment values dynamically to pass into the `env_vars` input.

A great improvement would be to make this possible by either supporting the use of a YAML config file like the `gcloud` CLI does, and/or supporting using GitHub Actions' `set-output` to pass a dynamic string in `KEY=VALUE,KEY2=VALUE2` format.

### Design

**Action YAML**

New `env_vars_file` input.

**Comment by bharathkkb** [comment]
Thanks for the feedback @ryan-blunden 
We are considering implementing a env file input as per https://github.com/google-github-actions/deploy-cloud-functions/issues/17#issuecomment-732428770
