### ISSUE TITLE
Allow unauthenticated invocations

### ISSUE THREAD

**Issue by DeryabinSergey** [google-github-actions/deploy-cloud-functions#350]
### TL;DR

Add param to set for HTTP trigger option Allow unauthenticated invocations

**Comment by mymyparty** [comment]
@sethvargo it is unclear whether it is already implemented or not, but this is extremely useful feature.
Any plans on this?

**Comment by sethvargo** [comment]
This is documented in the README. Right now, you'll need to make the service public after deployment. It will retain the permissions for subsequent deployments: https://github.com/google-github-actions/deploy-cloud-functions#allowing-unauthenticated-requests

**Comment by mymyparty** [comment]
@sethvargo oh sorry, i see :-) Thank you!

**Comment by neimad1985** [comment]
Hello, 

I would need clarifications on this please:

> This is documented in the README. Right now, you'll need to make the service public after deployment. It will retain the permissions for subsequent deployments: https://github.com/google-github-actions/deploy-cloud-functions#allowing-unauthenticated-requests

I read the readme which says
`The Cloud Functions product recommendation is that CI/CD systems not set or change settings for allowing unauthenticated invocations. New deployments are automatically private services, while deploying a revision of a public (unauthenticated) service will preserve the IAM setting of public (unauthenticated).`

But I am confused, what is the purpose then of setting `ingress_settings: ALLOW_ALL` ?

If this option exist, then it should have an effect, no ?
And if not, why does it exist ?

Thanks for clarifying, maybe I misunderstand the role of this setting.

Thank you

**Comment by sethvargo** [comment]
> But I am confused, what is the purpose then of setting `ingress_settings: ALLOW_ALL` ?

This controls whether traffic is allowed to the instance (IP-level firewall); it does not control whether the caller passes authentication to the request.


| Ingress Setting           | From VM in same VPC | From Internet
| ------------------------- | ------------------- | -------------
| `ALLOW_ALL`               | ✅                  | ✅
| `ALLOW_INTERNAL_ONLY`     | ✅                  | ❌ 
| `ALLOW_INTERNAL_AND_GCLB` | ✅                  | ⚠️ (only via LB)

Once the request _reaches_ the service, **then** _authorization_ applies.
