### ISSUE TITLE
Empty env_vars removes all existing env_vars

### ISSUE THREAD

**Issue by Doggie52** [google-github-actions/deploy-cloud-functions#38]
### TL;DR
Passing an empty `env_vars` removes all existing environment variables and leaves you with a GCF with no environment variables. Is this intentional? If it is, I think that should be made more clear in the readme.

**Expected behavior**
Leaving existing variables in place.

**Observed behavior**
Environment variables removed.

**Comment by bharathkkb** [comment]
Thanks for the report @Doggie52 
This is intended behavior as we expect users to maintain the function config in git. We should definitely update the docs to call this out. Happy to review a PR too.

**Comment by Doggie52** [comment]
Sure, have raised https://github.com/google-github-actions/deploy-cloud-functions/pull/40.
