### ISSUE TITLE
consider exposing the docker_registry option

### ISSUE THREAD

**Issue by eitansuez** [google-github-actions/deploy-cloud-functions#384]
### TL;DR

cloud functions v1 uses container registry by default.  container registry is being deprecated in favor of artifact registry.  the gcloud functions deploy command has an option [--docker-registry](https://cloud.google.com/sdk/gcloud/reference/beta/functions/deploy#--docker-registry) to control that.  i'd like to be able to set that flag from the github action deploy-cloud-functions

**Comment by eitansuez** [comment]
scanning the source, it looks like this option is already supported, perhaps just not documented in the readme.

**Comment by alessandrofajr** [comment]
> scanning the source, it looks like this option is already supported, perhaps just not documented in the readme.

sorry if it's a noob question: where in the YML file we should specify the option of docker-registry?

**Comment by eitansuez** [comment]
i think i was referring to the [documentation in the readme](https://github.com/google-github-actions/deploy-cloud-functions?tab=readme-ov-file#inputs).
