### ISSUE TITLE
Explain how the worker pool and provider should be configured

### ISSUE THREAD

**Issue by dsbowen** [google-github-actions/deploy-cloud-functions#403]
### TL;DR

It's unclear to me how the worker pool and provider should be configured.

### Detailed design

Trying to produce a minimal working example using this action, I keep running into:

```
google-github-actions/deploy-cloud-functions failed with: failed to upload zip file: Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).
```

It's difficult to interpret this error message. I followed the configuration instructions for the deployment service account and deployed the cloud function from the console using the deployment service account. So, I assume the issue lies with the worker pool and provider, but it's not clear how to configure these from the README.

**Comment by sethvargo** [comment]
Hi @dsbowen - it sounds like you're having trouble with authenticating. Have you look at the [Troubleshooting guide](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md)

**Comment by dsbowen** [comment]
Thanks, the troubleshooting guide did the trick!
