### ISSUE TITLE
Is it possible to deploy an onRun cloud function with this action?

### ISSUE THREAD

**Issue by trigonometric-act** [google-github-actions/deploy-cloud-functions#410]
Documentation is not very clear on how to deploy a function like in ts:

export const whatevername= functions.region('europe-west1').pubsub.schedule('0 1 * * *').timeZone('Europe/Madrid').onRun(async () => {
// code
})

Is it possible to do it with this action?

Any explanation would be much apreciated, thanks!

**Comment by sethvargo** [comment]
Hi @trigonometric-act - this function uses the Cloud Functions API to deploy functions. So if the Cloud Functions v1 API supports deploying those functions, then it will work.
