### ISSUE TITLE
Provide gcloud commands to setup deployment service account

### ISSUE THREAD

**Issue by FezVrasta** [google-github-actions/deploy-cloud-functions#432]
### TL;DR

I'm trying to setup a deployment service account using exclusively gcloud CLI but I keep hitting `The caller does not have permission`. (See [this StackOverflow question](https://stackoverflow.com/questions/78896153/the-caller-does-not-have-permission-when-trying-to-deploy-google-cloud-functio/78896883#78896883)).

It would be extremely useful if you could provide the gcloud commands needed to setup a service account able to deploy gen2 cloud functions.

**Comment by sethvargo** [comment]
You need to give the the service account `cloudfunctions.developer`: https://github.com/google-github-actions/test-infra/blob/0ce8ad437dfea114b6a7c85fa98ca76864a54f92/project_deploy-cloud-functions.tf#L55-L67

**Comment by sethvargo** [comment]
How are you authenticating?

**Comment by FezVrasta** [comment]
I'm using the `google-github-actions/auth@v2` with the `credentials_json` option. The json has been minified on a single row and is working properly, I was also able to deploy some nodes to a GKE cluster through the same deployment script.

**Comment by FezVrasta** [comment]
I just tried to deploy locally and it works for some reason

```
❯ gcloud auth activate-service-account --key-file=acct.json
Activated service account credentials for: [github-actions-production@<PROJECT_ID>.iam.gserviceaccount.com]
            
❯ gcloud functions deploy delivery-channels \
          --gen2 \
          --runtime=nodejs20 \
          --region=${LOCATION} \   
          --source=workspaces/delivery-channels \
          --trigger-http \
          --entry-point=delivery-channel \
          --allow-unauthenticated
Preparing function...done.                                                                                                                                                    
X Deploying function...                                                                                                                                                       
  - [Build] Build in progress... Logs are available at [...]                                                                                                                                                                 
  . [Service]                                                                                                                                                                 
  . [ArtifactRegistry]                                                                                                                                                        
  . [Healthcheck]                                                                                                                                                             
  . [Triggercheck]      
```

Are the commands I gave above effectively the same as doing:

```
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

  - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

 - name: Deploy Delivery Channels Cloud Function
        run: |-
          gcloud functions deploy delivery-channels \
          --gen2 \
          --runtime=nodejs20 \
          --region=${{ env.GCP_LOCATION }} \
          --source=workspaces/delivery-channels \
          --trigger-http \
          --entry-point=delivery-channel \
          --allow-unauthenticated
```

?

**Comment by sethvargo** [comment]
Can you please share your complete `action.yml`?

**Comment by FezVrasta** [comment]
Here, thanks for the help.
https://gist.github.com/FezVrasta/3bdb4ce811162556be15e35e072e4056

**Comment by FezVrasta** [comment]
I tried to SSH into the GitHub runner, created the acct.json file with my key, and ran the same commands I ran locally, but I get the same error I initially reported.

**Comment by sethvargo** [comment]
Are you sure it's the same service account? Also, I see a lot of intermingling of `env`, `vars`, and `secrets`. You have `env` defined, but then reference `vars` in a few places. Those are different things.

**Comment by FezVrasta** [comment]
Yes they are the same account. I used the same json...

The script reads the right secrets and vars. As I told you it works with the other deployment environment

**Comment by sethvargo** [comment]
> To reiterate, this deployment script works correctly when it targets my development environment (with its dedicated gcp project).

I'm not sure what you mean? Did you grant the service account permissions on both projects?

**Comment by FezVrasta** [comment]
Yes the permissions should be the same for both. I can't observe any differences.

**Comment by sethvargo** [comment]
Can you share the exact commands you're running when you SSH into the GHA runner? Ideally including the [debug logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging).

**Comment by FezVrasta** [comment]
This is the GHA runner:

![CleanShot 2024-08-21 at 10  10 29@2x](https://github.com/user-attachments/assets/2a9f9dec-3406-4eb4-895b-5afa0d637087)


This my local machine:

![CleanShot 2024-08-21 at 10  12 11@2x](https://github.com/user-attachments/assets/c8c83a3b-42ae-4d2b-b9fd-de051df9e676)

**Comment by FezVrasta** [comment]
Ah! After I updated the gcloud binary locally I started having the same exact error!

**Comment by sethvargo** [comment]
Can you try using `gcloud auth login --cred-file X --update-adc`? It's very strange that the gcloud version would affect authentication.

**Comment by FezVrasta** [comment]
I will try tomorrow and get back to you. I'm going to sleep now. Thanks again for the support you provided!

**Comment by FezVrasta** [comment]
@sethvargo using the `auth login` command doesn't change it, the last working version is 482.0.0

**Comment by sethvargo** [comment]
Hi @FezVrasta if the issue is 100% reproducible with just the `gcloud` command, then I think it'd be best to report that to the gcloud team: https://cloud.google.com/sdk/docs/getting-support

This GitHub Action installs gcloud and runs gcloud commands, but we don't have any control over the gcloud tool itself.
