### ISSUE TITLE
Increase function deploy timeout

### ISSUE THREAD

**Issue by xylo04** [google-github-actions/deploy-cloud-functions#45]
My function deployments tend to fail flakily (e.g. https://github.com/k0swe/kellog-func/actions/runs/561572062) due to timing out [here](https://github.com/google-github-actions/deploy-cloud-functions/blob/9741a482f5302ce81045d99d6dd1f9c765c6ad1d/src/cloudFunctionClient.ts#L317). The actual GCP deployment finishes successfully, but the GitHub workflow fails at this action. Can we increase or customize that timeout?

**Comment by bharathkkb** [comment]
fixed by #46
