### ISSUE TITLE
Resolve symlinks when zip:ing sourceDir

### ISSUE THREAD

**Issue by voxpelli** [google-github-actions/deploy-cloud-functions#66]
### TL;DR

Symlinks provides an easy to construct a `sourceDir` that that references select parts of a larger repository.

### Design

If one wants to share code among a couple of cloud functions in a repo, then symlinking in a shared folder would be an easy way to achieve that.

### References

#36: An opt out approach to assuring the right content gets uploaded rather than this opt in approach. (And #65 which fixes that I one and might make this one easier to solve)

**Comment by bharathkkb** [comment]
@voxpelli does deploying via the gcloud CLI follow symlinks?

**Comment by voxpelli** [comment]
@bharathkkb Not sure, I didn’t test that

**Comment by bharathkkb** [comment]
I did some testing and seems like gcloud resolves symlinks for files but not for dirs. I don't see an issue with supporting both and should be able to pass in the `followSymbolicLinks` option to accomplish this. @averikitsch any issues with supporting both?

**Comment by averikitsch** [comment]
> I did some testing and seems like gcloud resolves symlinks for files but not for dirs. I don't see an issue with supporting both and should be able to pass in the `followSymbolicLinks` option to accomplish this. @averikitsch any issues with supporting both?

This seems like this could have some inherent risks and not be a recommended best practice? We should connect with SME on this idea.

**Comment by sethvargo** [comment]
I'm 👎 on following symlinks

**Comment by bharathkkb** [comment]
@sethvargo should we aim to maintain parity with gcloud as it looked to be supported from my initial testing?

**Comment by sethvargo** [comment]
I'm really worried about supporting it from a security perspective. If I publish a repo with symlinks to `../../../../etc/passwd` and people blindly pull that in, we'd resolve that symlink and bundle `/etc/passwd` into the deployment.
