### ISSUE TITLE
Add ingress-settings option

### ISSUE THREAD

**Issue by thaonguyenct** [google-github-actions/deploy-cloud-functions#91]
### TL;DR
I want to deploy a CloudFunction that only allow ingress connection from internal or GLB `--ingress-settings internal-and-gclb `. But we don't have `ingress-settings` option.

### Design

It would be nice if we add `ingress-settings` option

https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--ingress-settings

Thank you!

**Comment by bharathkkb** [comment]
@thaonguyenct thanks for the FR. This should [be straightforward to add](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#ingresssettings). Happy to review a PR if someone else gets to it first.

**Comment by leblancfg** [comment]
For others coming to this issue from a related error: the possible values accepted by `ingress_settings` [are taken from the API reference](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions?hl=en_US#IngressSettings), not the `gcloud` implementation or what you might see in the console. Valid values are:

* `ALLOW_ALL`
* `ALLOW_INTERNAL_ONLY`
* `ALLOW_INTERNAL_AND_GCLB`
